// Extracts the original CGA sprite table and font from the reference port in old/
// into typed modules under src/sim/data/. Run once with `npm run extract`; the
// generated files are committed so old/ is never needed at build time.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import vm from 'node:vm';

const OLD = new URL('../old/src/', import.meta.url);
const OUT = new URL('../src/sim/data/', import.meta.url);
mkdirSync(OUT, { recursive: true });

function load(file, name) {
  const ctx = {};
  vm.createContext(ctx);
  vm.runInContext(readFileSync(new URL(file, OLD), 'utf8') + `\nthis.__out = ${name};`, ctx);
  return ctx.__out;
}

const header =
  '// Generated by tools/extract-data.mjs from the Digger Remastered JS port. Do not edit.\n' +
  '// Original graphics (c) 1983 Windmill Software; Digger Remastered by Andrew Jenner (GPL).\n';

// --- CGA sprite table: pairs of [bitmap, mask], indexed by sprite "ch" ---
const cga = load('cgagrafx.js', 'cgagrafx');
const arrays = [];
const ids = new Map();
const table = cga.cgatable.map((arr) => {
  if (!ids.has(arr)) {
    ids.set(arr, arrays.length);
    arrays.push(Array.from(arr));
  }
  return ids.get(arr);
});
writeFileSync(
  new URL('cgagrafx.ts', OUT),
  header +
    `const arrays: number[][] = ${JSON.stringify(arrays)};\n` +
    `const index: number[] = ${JSON.stringify(table)};\n` +
    `/** cgatable[ch*2] is the bitmap, cgatable[ch*2+1] the mask (2bpp packed, 4 px per byte). */\n` +
    `export const cgatable: number[][] = index.map((i) => arrays[i]);\n` +
    `/** Run-length encoded title screen. */\n` +
    `export const cgatitledat: number[] = ${JSON.stringify(Array.from(cga.cgatitledat))};\n`,
);

// --- Font ---
const alpha = load('alpha.js', 'alpha');
writeFileSync(
  new URL('alpha.ts', OUT),
  header +
    `/** 12-row x 3-byte glyphs for ASCII 32..127 (null where undefined). */\n` +
    `export const ascii2cga: (number[] | null)[] = ${JSON.stringify(
      alpha.ascii2cga.map((g) => (g ? Array.from(g) : null)),
    )};\n`,
);

console.log(`cgatable: ${table.length} entries (${arrays.length} unique arrays); font glyphs: ${alpha.ascii2cga.length}`);
